channels:
  - conda-forge
dependencies:
  - python<3.12
  - matplotlib>=3.4.2
  - Cartopy>=0.21.0
  - Shapely>=1.8.0,<2.0.0
  - numpy>=1.21.5
  - netCDF4>=1.5.8
  - geopandas>=0.10.2
  - Fiona>=1.8.20
